# Generated by Django 3.2.7 on 2021-09-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='simulado',
        ),
        migrations.AddField(
            model_name='simulado',
            name='questoes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='simulados.questao'),
        ),
    ]
