# Generated by Django 3.2.7 on 2021-09-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0002_auto_20210921_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='questao',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
