# Generated by Django 3.2.7 on 2021-09-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0004_auto_20210921_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado'),
        ),
    ]
